/*Modelagem Básica
ENTIDADE = TABELA
CAMPOS = ATRIBUTOS
*/

Cliente

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/*PROCESSOS DE MODELAGEM*/
/*FASE 1 E FASE 2 - AD ADM DE DADOS*/
MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/*FASE 03 - DBA / AD*/
MODELAGEM FISICA - SCRIPTS DE BANCO

/*INICIANDO A MODELAGEM FÍSICA*/

/*CRIANDO BANCO DE DADOS*/
CREATE DATABASE PROJETO;

/*CONECTANDO-SE AO BANCO*/
USE PROJETO;

/*CRIANDO A TABELA DE CLIENTES*/

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),	
	CPF VARCHAR(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/*VERIFICANDO AS TABELAS DO BANCO*/
SHOW TABLES;

/*DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA*/
DESC CLIENTE;


/*Para caracteres literais temos -> CHAR E VARCHAR
  PARA NÚMEROS TEMOS -> FLOAT E INT
  FOTOS E DOCUMENTOS TEMOS -> BLOB
  TEXTOS EXTENSOS TEMOS O -> TEXT
  
  CADA CARACTER = 1BYTE
  
  CHAR USADO PARA QUANDO: O NÚMERO DE CARACTERERS DA COLUNA NUNCA FOR VARIANTE
  
*/
/*ENUM = ENUMERAÇÃO
  ENUM ESTÁ PRESENTE SOMENTE NO MYSQL
  EM BANCOS DE DADOS COMO ORACLE/SQL SERVER
  IMPLANTADO COMO ALGO QUE SE CHAMA CONSTRAINTS
  
  TIPOS NUMERICOS
  
  FLOAT PARA REAIS
  INT PARA INTEIROS
  
  FLOAT(10,2) 10 CASAS DECIMAIS NO TOTAL SENDO 2 DELAS APÓS A VIRGULA
  INT ACEITA SOMENTE NÚMEROS INTEIROS MAIOR NUMERO DE ALGARISMOS DO TIPO INT É DE 11 DIGITOS
  
  NÚMEROS QUE NÃO NECESSITAM DE CÁLCULOS PODEM SER TIPADOS COMO VARCHAR
  CPF CONSTUMAMOS A COLOCAR COMO VARCHAR E NÃO COMO INT
*/

/*
a junção de todas as colunas formam um REGISTRO ou TUPLA
  	
	use projeto;
	
	show tables;
	
	exibindo a estrutura de uma tabela
	desc cliente; ->  DESC VEM DE DESCRIBE	
	
	FORMA 01- OMITINDO AS COLUNAS
	INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');
*/
INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/*FORMA 02*/
INSERT INTO CLIENTE(NOME,SEXO,EMAIL,CPF,TELEFONE,ENDERECO) VALUES('DIEGO','M','DIEGO-VESPA2020@OUTLOOK.COM.BR','12332156782',988776655,'AVE.REGISTO MANOLF,169 - JD.BR-SP');
INSERT INTO CLIENTE(NOME,SEXO,EMAIL,CPF,TELEFONE,ENDERECO) VALUES('SUELI','F','SUELI-VESPA@OUTLOOK.COM.BR','12332156782',988776655,'AVE.REGISTO MANOLF,169 - JD.BR-SP');

/*SELEÇÃO PROJEÇÃO E JUNÇÃO*/

SELECT NOW() AS DATA_HORA;
SELECT NOW() AS DATA_HORA, 'DIEGO' AS PROFESSOR;

SELECT NOME AS CLIENTE,SEXO,EMAIL FROM CLIENTE;
SELECT NOME,SEXO,EMAIL, ENDERECO FROM CLIENTE;
SELECT NOME,SEXO,EMAIL, ENDERECO, NOW() AS DATA_HORA FROM CLIENTE;

/*QUANDO FILTRAMOS POR COLUNA ESTAMOS PROJETANDO*/

/*
	FILTRANDO
*/
SELECT NOME, SEXO FROM CLIENTE WHERE SEXO = 'M';
SELECT NOME, ENDERECO FROM CLIENTE WHERE SEXO = 'M';

/*BANCO DE DADOS = TEORIA DOS CONJUNTOS*/
/*EMPTY SET = SET DE DADOS VAZIO*/

/*UTILIZANDO O LIKE*/

SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO LIKE 'SP';

/*CARACTER CORINGA % -> QUALQUER COISA*/
SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO LIKE '%SP';
SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO LIKE 'SP%';
SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO LIKE '%CENTRO%';
SELECT NOME, SEXO FROM CLIENTE WHERE ENDERECO LIKE '%CENTRO%';

